diamante_automation:
    entities:
      ticket:
        class: "Diamante\DeskBundle\Entity\Ticket"
        frontend_label: diamante.desk.ticket.entity_label
        properties:
          status:
            frontend_label: diamante.desk.ticket.status.label
            frontend_options: "^\\Diamante\\DeskBundle\\Model\\Ticket\\Status::getValueToLabelMap"
            type: status
          priority:
            frontend_label: diamante.desk.ticket.priority.label
            frontend_options: "^\\Diamante\\DeskBundle\\Model\\Ticket\\Priority::getValueToLabelMap"
            type: priority
          source:
            frontend_label: diamante.desk.ticket.source.label
            frontend_options: "^\\Diamante\\DeskBundle\\Model\\Ticket\\Source::getValueToLabelMap"
            type: source
          subject:
            frontend_label: diamante.desk.ticket.subject.label
            type: string
          description:
            frontend_label: diamante.desk.ticket.description.label
            type: string
          sent_to:
            frontend_label: diamante.desk.ticket.created_via_email
            type: virtual
            accessor: diamante.ticket.email_processing_message_reference.repository::getEndpointByTicket

      comment:
        class: "Diamante\DeskBundle\Entity\Comment"
        frontend_label: diamante.desk.comment.entity_label
        properties:
          content:
            frontend_label: diamante.desk.comment.content.label
            type: string

    conditions:
      sent_to:
        class: "Diamante\AutomationBundle\Rule\Condition\Expression\Veq"
        frontend_label: diamante.desk.automation.condition.sent_to

    actions:
      move_to_branch:
        id: @diamante.desk.automation.action.move_to_branch
        frontend_label: diamante.desk.automation.action.move_to_branch
        data_types: ['virtual']

parameters:
  diamante.automation.action.move_to_branch.class: Diamante\DeskBundle\Automation\Action\MoveToBranchAction

services:
  diamante.automation.action.move_to_branch:
    class: %diamante.automation.action.move_to_branch.class%
    arguments: @doctrine